name: Build

on:
  pull_request:
    branches: ["**"]
  merge_group:
  workflow_dispatch: # Allow manual triggering

jobs:
  build-artifacts:
    name: Build desktop + extension artifacts
    uses: ./.github/workflows/packages.yml
    with:
      mode: build
    secrets: inherit
